version: "3.9"
services:
  rest-api:
    build: ./rest_api/
    ports:
      - "8000:80"
    environment:
      - PROMETHEUS_URL

  prometheus:
    build: ./prometheus/
    ports:
      - "9090:9090"

  mock-kong-gateways:
    build: ./mock_kong_gateways/
    ports:
      - "9000:8000"
      - "9001:8001"
      - "9443:8443"
      - "9444:8444"

